repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff code formatting
        entry: poetry run ruff format --check .
        language: system
        types: [python]

      - id: ruff-lint
        name: ruff linting
        entry: poetry run ruff check .
        language: system
        types: [python]

      - id: mypy
        name: mypy type checking
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false
