---
services:
  postgres:
    image: docker.io/library/postgres:18.1
    restart: always
    container_name: postgres
    shm_size: 128mb
    ports:
      - "127.0.0.1:17432:5432"
    volumes:
      - pg18_data:/var/lib/postgresql/18/docker
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - ../../env/postgres.env
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  app:
    image: leprekorn/allocation:0.0.1
    restart: always
    container_name: allocation
    ports:
      - "127.0.0.1:8000:80"
    depends_on:
      - postgres
    env_file:
      - ../../env/allocation.env
    volumes:
      - ../../src/:/app/src/

volumes:
  pg18_data:
    driver: local
    name: pg18_data
